/* eslint-disable no-restricted-globals */

// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other
// code you'd like.
// You can also remove this file if you'd prefer not to use a
// service worker, and the Workbox build step will be skipped.

import { clientsClaim } from "workbox-core";
import { ExpirationPlugin } from "workbox-expiration";
import { precacheAndRoute, createHandlerBoundToURL } from "workbox-precaching";
import { registerRoute } from "workbox-routing";
import { CacheFirst, StaleWhileRevalidate } from "workbox-strategies";
import { RangeRequestsPlugin } from "workbox-range-requests";

clientsClaim();

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
precacheAndRoute(self.__WB_MANIFEST);

// Set up App Shell-style routing, so that all navigation requests
// are fulfilled with your index.html shell. Learn more at
// https://developers.google.com/web/fundamentals/architecture/app-shell
const fileExtensionRegexp = new RegExp("/[^/?]+\\.[^/]+$");
registerRoute(
  // Return false to exempt requests from being fulfilled by index.html.
  ({ request, url }) => {
    // If this isn't a navigation, skip.
    if (request.mode !== "navigate") {
      return false;
    }

    // If this is a URL that starts with /_, skip.
    if (
      url.pathname.startsWith("/_") ||
      url.pathname.startsWith("/static") ||
      url.pathname.startsWith("/api/v1") ||
      url.pathname.startsWith("/api/admin")
    ) {
      return false;
    }

    // If this looks like a URL for a resource, because it contains
    // a file extension, skip.
    if (url.pathname.match(fileExtensionRegexp)) {
      return false;
    } // Return true to signal that we want to use the handler.

    return true;
  },
  createHandlerBoundToURL(process.env.PUBLIC_URL + "/index.html")
);

// An example runtime caching route for requests that aren't handled by the
// precache, in this case same-origin .png requests like those from in public/
registerRoute(
  // Add in any other file extensions or routing criteria as needed.
  ({ url }) =>
    url.origin === self.location.origin &&
    url.pathname.endsWith(".png") &&
    !url.pathname.startsWith("/api/media") &&
    !url.pathname.startsWith("/api/static"),
  new StaleWhileRevalidate({
    cacheName: "images",
    plugins: [
      // Ensure that once this runtime cache reaches a maximum size the
      // least-recently used images are removed.
      new ExpirationPlugin({ maxEntries: 50 }),
    ],
  })
);

registerRoute(
  ({ url }) =>
    url.pathname.startsWith("/api/media") ||
    url.pathname.startsWith("/api/static"),
  new StaleWhileRevalidate({
    cacheName: "api-media-static",
    plugins: [new ExpirationPlugin({ maxEntries: 100 })],
  })
);

// Prefetch /api/static/verona.pmtiles on the first visit to the home page
self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open("verona-pmtiles-cache").then((cache) => {
      return cache.add("/api/static/verona.pmtiles");
    })
  );
});

// Handle range requests for /api/static/verona.pmtiles
registerRoute(
  ({ url }) => url.pathname === "/api/static/verona.pmtiles",
  new CacheFirst({
    cacheName: "verona-pmtiles-cache",
    plugins: [
      new RangeRequestsPlugin(), // Add support for range requests
      new ExpirationPlugin({ maxEntries: 1 }),
    ],
  })
);

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") {
    self.skipWaiting();
  }
});

// Any other custom service worker logic can go here.
// TODO: precache on pm tiles??
